color: null
fieldLayouts:
  674bd2a7-b6f9-4f9c-a142-30a81c4f5962:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1b91e6e0-fd82-41bd-9673-dfd72f16e284
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5496f37d-fc7c-4c76-b53e-35397608cd29 # Hero Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42a33263-a011-43ae-9a62-23c8b1b96387
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cfd245f8-e6f7-4ad2-a898-95d413f3df58 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7b2ecd6-268d-4019-ab00-09b4a658bc0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15fdbaee-24ec-47d8-a795-da2ba2ca6b5a
        userCondition: null
handle: about
hasTitleField: true
icon: ''
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
