color: null
fieldLayouts:
  45a38803-6a3e-41a8-93e4-e450cb440d14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6473ecab-a33f-4054-926b-2cf75341d0b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66950751-f7df-4159-8f3b-edad9c7d4661 # Photos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72cebabb-5f55-4653-bf91-f048a51a4ee9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7603898-3725-4c58-bfa8-2f44344b4ced # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0c35e7b-0eb4-49cd-b703-2925b3d3666b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8fb254e-043f-41e3-b7f5-dc65605407ee # Short Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 788a547a-303d-4d38-8295-b2092d6a9d94
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 50ebbbd4-f8bf-4687-a072-88fee53f7fba
        userCondition: null
handle: stories
hasTitleField: true
icon: ''
name: Stories
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
