altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  9430d7e2-b2f7-45fc-b65d-6d2a9dd4d73d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c04ee3bb-f6d0-4027-9aa9-3e72d40add6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11d71189-acea-427d-b53b-1b72312de6b1
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: uploads
transformSubpath: ''
