defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0c54e1ca-22d9-4f84-8a0d-b0019ce8d179 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  59436fea-6b90-4cee-a947-21b3b6e4f233: # Scuti
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
