defaultPlacement: end
enableVersioning: true
entryTypes:
  - 1d8ad413-14ee-4179-9864-2e89321c94d7 # Stories
handle: stories
maxAuthors: 1
name: Stories
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  59436fea-6b90-4cee-a947-21b3b6e4f233: # Scuti
    enabledByDefault: true
    hasUrls: true
    template: stories/_entry
    uriFormat: 'stories/{slug}'
type: channel
